#nome do workflow
name: Deploy no Github Pages
#somente executa com push na branch main
on:
 push:
   branches:
     - main
jobs:
 #nome do job
 deploy:
   #sistema operacional
   runs-on: ubuntu-latest
   #step para obter o conteúdo do repositório
   steps:
     - name: Obtem repositorio
       uses: actions/checkout@v2


     - name: Instala o NodeJS
       uses: actions/setup-node@v2
       with:
         node-version: 14


     - name: Deploy no Github Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         #token para autenticação criado automaticamente
         #pelo github actions
         personal_token: ${{ secrets.ACTIONS_TOKEN }}
         #diretório de origem do conteúdo
         publish_dir: ./build